<a href="https://colab.research.google.com/github/scottzig/pytorch_examples/blob/main/pytorch_tensor_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.empty(3,2,1)
print(x)

tensor([[[5.9269e-36],
         [0.0000e+00]],

        [[1.5975e-43],
         [1.3873e-43]],

        [[1.4574e-43],
         [6.4460e-44]]])


In [ ]:
x_2 = torch.rand(3,2,1)
print(x_2)

tensor([[[0.7800],
         [0.9620]],

        [[0.7338],
         [0.4549]],

        [[0.8788],
         [0.0180]]])


In [ ]:
x_3 = torch.zeros(3,2,1)
print(x_3)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])


In [ ]:
x_4 = torch.ones(3,2,1,dtype = torch.int)
print(x_4)
print(x_4.dtype)

tensor([[[1],
         [1]],

        [[1],
         [1]],

        [[1],
         [1]]], dtype=torch.int32)
torch.int32


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y # or z = torch.add(x,y)
print(z)
y.add_(x) # in place addition
print(y)

tensor([[0.4700, 0.4095],
        [0.3127, 0.8193]])
tensor([[0.0277, 0.8444],
        [0.9034, 0.3829]])
tensor([[0.4977, 1.2539],
        [1.2161, 1.2022]])
tensor([[0.4977, 1.2539],
        [1.2161, 1.2022]])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x * y # element by element multiplication
print(z)

tensor([[0.4463, 0.2713],
        [0.1580, 0.5254]])
tensor([[0.1254, 0.8842],
        [0.5176, 0.6612]])
tensor([[0.0560, 0.2399],
        [0.0818, 0.3474]])


In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:,0]) # slice a tensor as in numpy


tensor([[0.4787, 0.0653, 0.8957],
        [0.6310, 0.1208, 0.9857],
        [0.6250, 0.5148, 0.7952],
        [0.3365, 0.4535, 0.6528],
        [0.7120, 0.0307, 0.6629]])
tensor([0.4787, 0.6310, 0.6250, 0.3365, 0.7120])


In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy() # convert a torch tensor to a numpy array
print(b)
print(type(b))

a.add_(1) # add one to each element of the tensor a
print(a)
print(b) # the tensor a and numpy array b point to the same memory location

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a) # convert a numpy array to a torch tensor
print(b)

a += 1 # add one to each element of numpy array a
print(a)
print(b) # again, the numpy array a and the torch tensor b point to the same location in memory

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available(): # check if we have access to the gpu
  device = torch.device("cuda")
  x = torch.ones(4, device=device) # create a torch tensor on the gpu
  y = torch.ones(4)
  y = y.to(device) # these two lines make a torch tensor on the cpu then move it to the gpu
  z = x + y # add two tensors on the gpu
  # can't convert this to numpy since numpy doesn't have access to the gpu!
  z = z.to("cpu") # move z back to the cpu

In [ ]:
x = torch.ones(5, requires_grad=True) # tells torch to keep track of gradient information
print(x)